### ISSUE TITLE
Deprecated Constant TEMP_CELSIUS

### ISSUE THREAD

**Issue by kozfelipe** [yangqian/hass-cozylife#33]
> TEMP_CELSIUS was used from cozylife, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfTemperature.CELSIUS instead, please report it to the author of the 'cozylife' custom integration

reporting deprecated constant which will be removed

**Comment by gitTerracide** [comment]
updated to 2025.1 today... my cozylights stopped working.

Platform error 'light' from integration 'cozylife' - cannot import name 'TEMP_CELSIUS' from 'homeassistant.const' (/usr/src/homeassistant/homeassistant/const.py).

Seems cozylife does not get much attention by the author/owners. I'm no coder but my understanding is the the respective .py needs to be updated. Going to try hack my way through that... like a 1600s jungle expidition... :>

**Comment by MedouTwelve** [comment]
> updated to 2025.1 today... my cozylights stopped working.
> 
> Platform error 'light' from integration 'cozylife' - cannot import name 'TEMP_CELSIUS' from 'homeassistant.const' (/usr/src/homeassistant/homeassistant/const.py).
> 
> Seems cozylife does not get much attention by the author/owners. I'm no coder but my understanding is the the respective .py needs to be updated. Going to try hack my way through that... like a 1600s jungle expidition... :>

Hi dude. Same went for me. After updating to 2025.1.0, got the same error message. I’m a little dev guy but I’ve just dive into Python and HA code. Too fresh for me still to figure it out. 
But I’ll give it a try as well.

First to find advise the other(s) ! 😜
Did put an « s » into brackets as any help from the community would be much appreciated… 

Thx in advance 🙏

**Comment by soulripper13** [comment]
This is a fixed code for switches only
`"""Platform for sensor integration."""
from __future__ import annotations
import logging
from datetime import timedelta
import asyncio

from homeassistant.components.switch import SwitchEntity
from homeassistant.core import HomeAssistant
from homeassistant.helpers.entity_platform import AddEntitiesCallback
from homeassistant.helpers.typing import ConfigType, DiscoveryInfoType
from homeassistant.helpers.event import async_track_time_interval

from .tcp_client import tcp_client
from .const import DOMAIN

SCAN_INTERVAL = timedelta(seconds=20)

_LOGGER = logging.getLogger(__name__)

async def async_setup_platform(
    hass: HomeAssistant,
    config: ConfigType,
    async_add_entities: AddEntitiesCallback,
    discovery_info: DiscoveryInfoType | None = None
) -> None:
    """Set up the sensor platform."""
    _LOGGER.info('Setting up CozyLife switches')

    switches = []

    # Create switch entities for each configuration item
    for item in config.get('switches', []):
        client = tcp_client(item.get('ip'))
        client._device_id = item.get('did')
        client._pid = item.get('pid')
        client._dpid = item.get('dpid')
        client._device_model_name = item.get('dmn')
        switches.append(CozyLifeSwitch(client, hass, 'wippe1'))

    for item in config.get('switches2', []):
        client = tcp_client(item.get('ip'))
        client._device_id = item.get('did')
        client._pid = item.get('pid')
        client._dpid = item.get('dpid')
        client._device_model_name = item.get('dmn')

        # Create two entities for each switch, one for each rocker
        switches.append(CozyLifeSwitch(client, hass, 'wippe1'))
        switches.append(CozyLifeSwitch(client, hass, 'wippe2'))

    # Add all switches to Home Assistant
    async_add_entities(switches)

    # Initialize TCP connections
    for switch in switches:
        await switch.async_initialize()

    # Set up periodic updates
    async def async_update(now=None):
        for switch in switches:
            await switch.async_update()
    async_track_time_interval(hass, async_update, SCAN_INTERVAL)

class CozyLifeSwitch(SwitchEntity):
    """Representation of a CozyLife switch."""

    def __init__(self, tcp_client: tcp_client, hass: HomeAssistant, wippe: str) -> None:
        """Initialize the switch."""
        self._tcp_client = tcp_client
        self.hass = hass
        self._wippe = wippe
        self._unique_id = f"{tcp_client.device_id}_{wippe}"
        self._name = f"{tcp_client.device_id[-4:]} {wippe}"
        self._attr_is_on = False
        self._state = None

    async def async_initialize(self) -> None:
        """Initialize the TCP connection."""
        await self.hass.async_add_executor_job(self._tcp_client._initSocket)

    async def async_update(self) -> None:
        """Update the switch state."""
        try:
            self._state = await self.hass.async_add_executor_job(self._tcp_client.query)
            _LOGGER.debug(f"State update for {self._name}: {self._state}")
            if self._state:
                if self._wippe == 'wippe1':
                    self._attr_is_on = (self._state['1'] & 0x01) == 0x01
                elif self._wippe == 'wippe2':
                    self._attr_is_on = (self._state['1'] & 0x02) == 0x02
        except Exception as e:
            _LOGGER.error(f"Failed to update state for {self._name}: {e}")

    @property
    def unique_id(self) -> str:
        """Return a unique ID."""
        return self._unique_id

    @property
    def name(self) -> str:
        """Return the name of the switch."""
        return f"cozylife:{self._name}"

    @property
    def available(self) -> bool:
        """Return if the device is available."""
        return self._tcp_client._connect

    @property
    def is_on(self) -> bool:
        """Return True if the switch is on."""
        return self._attr_is_on

    async def async_turn_on(self, **kwargs: Any) -> None:
        """Turn the switch on."""
        try:
            if self._wippe == 'wippe1':
                await self.hass.async_add_executor_job(self._tcp_client.control, {'1': self._state['1'] | 0x01})
            elif self._wippe == 'wippe2':
                await self.hass.async_add_executor_job(self._tcp_client.control, {'1': self._state['1'] | 0x02})
            self._attr_is_on = True
        except Exception as e:
            _LOGGER.error(f"Failed to turn on {self._name}: {e}")

    async def async_turn_off(self, **kwargs: Any) -> None:
        """Turn the switch off."""
        try:
            if self._wippe == 'wippe1':
                await self.hass.async_add_executor_job(self._tcp_client.control, {'1': self._state['1'] & ~0x01})
            elif self._wippe == 'wippe2':
                await self.hass.async_add_executor_job(self._tcp_client.control, {'1': self._state['1'] & ~0x02})
            self._attr_is_on = False
        except Exception as e:
            _LOGGER.error(f"Failed to turn off {self._name}: {e}")`

**Comment by soulripper13** [comment]
"""Platform for sensor integration."""
from __future__ import annotations
import logging
from datetime import timedelta
import asyncio

from homeassistant.components.switch import SwitchEntity
from homeassistant.core import HomeAssistant
from homeassistant.helpers.entity_platform import AddEntitiesCallback
from homeassistant.helpers.typing import ConfigType, DiscoveryInfoType
from homeassistant.helpers.event import async_track_time_interval

from .tcp_client import tcp_client
from .const import DOMAIN

SCAN_INTERVAL = timedelta(seconds=20)

_LOGGER = logging.getLogger(__name__)

async def async_setup_platform(
    hass: HomeAssistant,
    config: ConfigType,
    async_add_entities: AddEntitiesCallback,
    discovery_info: DiscoveryInfoType | None = None
) -> None:
    """Set up the sensor platform."""
    _LOGGER.info('Setting up CozyLife switches')

    switches = []

    # Create switch entities for each configuration item
    for item in config.get('switches', []):
        client = tcp_client(item.get('ip'))
        client._device_id = item.get('did')
        client._pid = item.get('pid')
        client._dpid = item.get('dpid')
        client._device_model_name = item.get('dmn')
        switches.append(CozyLifeSwitch(client, hass, 'wippe1'))

    for item in config.get('switches2', []):
        client = tcp_client(item.get('ip'))
        client._device_id = item.get('did')
        client._pid = item.get('pid')
        client._dpid = item.get('dpid')
        client._device_model_name = item.get('dmn')

        # Create two entities for each switch, one for each rocker
        switches.append(CozyLifeSwitch(client, hass, 'wippe1'))
        switches.append(CozyLifeSwitch(client, hass, 'wippe2'))

    # Add all switches to Home Assistant
    async_add_entities(switches)

    # Initialize TCP connections
    for switch in switches:
        await switch.async_initialize()

    # Set up periodic updates
    async def async_update(now=None):
        for switch in switches:
            await switch.async_update()
    async_track_time_interval(hass, async_update, SCAN_INTERVAL)

class CozyLifeSwitch(SwitchEntity):
    """Representation of a CozyLife switch."""

    def __init__(self, tcp_client: tcp_client, hass: HomeAssistant, wippe: str) -> None:
        """Initialize the switch."""
        self._tcp_client = tcp_client
        self.hass = hass
        self._wippe = wippe
        self._unique_id = f"{tcp_client.device_id}_{wippe}"
        self._name = f"{tcp_client.device_id[-4:]} {wippe}"
        self._attr_is_on = False
        self._state = None

    async def async_initialize(self) -> None:
        """Initialize the TCP connection."""
        await self.hass.async_add_executor_job(self._tcp_client._initSocket)

    async def async_update(self) -> None:
        """Update the switch state."""
        try:
            self._state = await self.hass.async_add_executor_job(self._tcp_client.query)
            _LOGGER.debug(f"State update for {self._name}: {self._state}")
            if self._state:
                if self._wippe == 'wippe1':
                    self._attr_is_on = (self._state['1'] & 0x01) == 0x01
                elif self._wippe == 'wippe2':
                    self._attr_is_on = (self._state['1'] & 0x02) == 0x02
        except Exception as e:
            _LOGGER.error(f"Failed to update state for {self._name}: {e}")

    @property
    def unique_id(self) -> str:
        """Return a unique ID."""
        return self._unique_id

    @property
    def name(self) -> str:
        """Return the name of the switch."""
        return f"cozylife:{self._name}"

    @property
    def available(self) -> bool:
        """Return if the device is available."""
        return self._tcp_client._connect

    @property
    def is_on(self) -> bool:
        """Return True if the switch is on."""
        return self._attr_is_on

    async def async_turn_on(self, **kwargs: Any) -> None:
        """Turn the switch on."""
        try:
            if self._wippe == 'wippe1':
                await self.hass.async_add_executor_job(self._tcp_client.control, {'1': self._state['1'] | 0x01})
            elif self._wippe == 'wippe2':
                await self.hass.async_add_executor_job(self._tcp_client.control, {'1': self._state['1'] | 0x02})
            self._attr_is_on = True
        except Exception as e:
            _LOGGER.error(f"Failed to turn on {self._name}: {e}")

    async def async_turn_off(self, **kwargs: Any) -> None:
        """Turn the switch off."""
        try:
            if self._wippe == 'wippe1':
                await self.hass.async_add_executor_job(self._tcp_client.control, {'1': self._state['1'] & ~0x01})
            elif self._wippe == 'wippe2':
                await self.hass.async_add_executor_job(self._tcp_client.control, {'1': self._state['1'] & ~0x02})
            self._attr_is_on = False
        except Exception as e:
            _LOGGER.error(f"Failed to turn off {self._name}: {e}")

**Comment by screem20056** [comment]
> i fixed it for me change the following lines in /homeassistant/custom_components/cozylife/light.py
> 
> line 36 from homeassistant.const import UnitOfTemperature, CONF_EFFECT
> 
> in /homeassistant/custom_components/cozylife/switch.py
> 
> line 10 from homeassistant.const import UnitOfTemperature

many thanks :) it works fine now really appreciate it
brilliant

**Comment by MedouTwelve** [comment]
> i fixed it for me change the following lines in /homeassistant/custom_components/cozylife/light.py
> 
> line 36 from homeassistant.const import UnitOfTemperature, CONF_EFFECT
> 
> in /homeassistant/custom_components/cozylife/switch.py
> 
> line 10 from homeassistant.const import UnitOfTemperature

@overnite22 I gave it a try and works like a charm for me as well! 
Thanks a lot man. You rock bro!

This should be pushed as a commit. 

@yangqian Please show up if you're still alive... ;-p
Could you please include these 2 fixes in next release? Thx in advance 

Peace

**Comment by kozfelipe** [comment]
that's good to know there is a workaround.
too bad this repo has its last pull 5 months ago

**Comment by gxaris** [comment]
> UnitOfTemperature

I wish it would also work for me :(
I did the changes in the files, restarted HA multiple times, nothing, my lights are still not recognised

**Comment by vokomarov** [comment]
> i fixed it for me change the following lines in /homeassistant/custom_components/cozylife/light.py
> 
> line 36 from homeassistant.const import UnitOfTemperature, CONF_EFFECT
> 
> in /homeassistant/custom_components/cozylife/switch.py
> 
> line 10 from homeassistant.const import UnitOfTemperature

Thanks @overnite22 , works for me.

We might see more similar issues in feature HA updates according to these logs

```
2025-01-11 11:18:07.115 WARNING (MainThread) [homeassistant.components.light] Entity None (<class 'custom_components.cozylife.light.CozyLifeLight'>) is using deprecated supported features values which will be removed in HA Core 2025.1. Instead it should use <LightEntityFeature.EFFECT|TRANSITION: 36> and color modes, please report it to the author of the 'cozylife' custom integration and reference https://developers.home-assistant.io/blog/2023/12/28/support-feature-magic-numbers-deprecation
2025-01-11 11:18:07.115 WARNING (MainThread) [homeassistant.components.light] None (<class 'custom_components.cozylife.light.CozyLifeLight'>) sets invalid supported color modes {'brightness', 'onoff', 'hs'}, this will stop working in Home Assistant Core 2025.3, please report it to the author of the 'cozylife' custom integration
```

**Comment by MedouTwelve** [comment]
I saw that as well. I really need to dig into it for the coding... 🤓
Maybe we'll have to create our own fork if no sign from the author. 

Wait and see! 😜

Peace.

**Comment by gitTerracide** [comment]
Thank you! Seems I was on the right track. Will try this evening.
Appreciate your help!

**Comment by J30789** [comment]
> Below is the fixed code for switches only:
> 
> """Platform for sensor integration.""" from **future** import annotations import logging from datetime import timedelta import asyncio
> 
> from homeassistant.components.switch import SwitchEntity from homeassistant.core import HomeAssistant from homeassistant.helpers.entity_platform import AddEntitiesCallback from homeassistant.helpers.typing import ConfigType, DiscoveryInfoType from homeassistant.helpers.event import async_track_time_interval
> 
> from .tcp_client import tcp_client from .const import DOMAIN
> 
> SCAN_INTERVAL = timedelta(seconds=20)
> 
> _LOGGER = logging.getLogger(**name**)
> 
> async def async_setup_platform( hass: HomeAssistant, config: ConfigType, async_add_entities: AddEntitiesCallback, discovery_info: DiscoveryInfoType | None = None ) -> None: """Set up the sensor platform.""" _LOGGER.info('Setting up CozyLife switches')
> 
> ```
> switches = []
> 
> # Create switch entities for each configuration item
> for item in config.get('switches', []):
>     client = tcp_client(item.get('ip'))
>     client._device_id = item.get('did')
>     client._pid = item.get('pid')
>     client._dpid = item.get('dpid')
>     client._device_model_name = item.get('dmn')
>     switches.append(CozyLifeSwitch(client, hass, 'wippe1'))
> 
> for item in config.get('switches2', []):
>     client = tcp_client(item.get('ip'))
>     client._device_id = item.get('did')
>     client._pid = item.get('pid')
>     client._dpid = item.get('dpid')
>     client._device_model_name = item.get('dmn')
> 
>     # Create two entities for each switch, one for each rocker
>     switches.append(CozyLifeSwitch(client, hass, 'wippe1'))
>     switches.append(CozyLifeSwitch(client, hass, 'wippe2'))
> 
> # Add all switches to Home Assistant
> async_add_entities(switches)
> 
> # Initialize TCP connections
> for switch in switches:
>     await switch.async_initialize()
> 
> # Set up periodic updates
> async def async_update(now=None):
>     for switch in switches:
>         await switch.async_update()
> async_track_time_interval(hass, async_update, SCAN_INTERVAL)
> ```
> 
> class CozyLifeSwitch(SwitchEntity): """Representation of a CozyLife switch."""
> 
> ```
> def __init__(self, tcp_client: tcp_client, hass: HomeAssistant, wippe: str) -> None:
>     """Initialize the switch."""
>     self._tcp_client = tcp_client
>     self.hass = hass
>     self._wippe = wippe
>     self._unique_id = f"{tcp_client.device_id}_{wippe}"
>     self._name = f"{tcp_client.device_id[-4:]} {wippe}"
>     self._attr_is_on = False
>     self._state = None
> 
> async def async_initialize(self) -> None:
>     """Initialize the TCP connection."""
>     await self.hass.async_add_executor_job(self._tcp_client._initSocket)
> 
> async def async_update(self) -> None:
>     """Update the switch state."""
>     try:
>         self._state = await self.hass.async_add_executor_job(self._tcp_client.query)
>         _LOGGER.debug(f"State update for {self._name}: {self._state}")
>         if self._state:
>             if self._wippe == 'wippe1':
>                 self._attr_is_on = (self._state['1'] & 0x01) == 0x01
>             elif self._wippe == 'wippe2':
>                 self._attr_is_on = (self._state['1'] & 0x02) == 0x02
>     except Exception as e:
>         _LOGGER.error(f"Failed to update state for {self._name}: {e}")
> 
> @property
> def unique_id(self) -> str:
>     """Return a unique ID."""
>     return self._unique_id
> 
> @property
> def name(self) -> str:
>     """Return the name of the switch."""
>     return f"cozylife:{self._name}"
> 
> @property
> def available(self) -> bool:
>     """Return if the device is available."""
>     return self._tcp_client._connect
> 
> @property
> def is_on(self) -> bool:
>     """Return True if the switch is on."""
>     return self._attr_is_on
> 
> async def async_turn_on(self, **kwargs: Any) -> None:
>     """Turn the switch on."""
>     try:
>         if self._wippe == 'wippe1':
>             await self.hass.async_add_executor_job(self._tcp_client.control, {'1': self._state['1'] | 0x01})
>         elif self._wippe == 'wippe2':
>             await self.hass.async_add_executor_job(self._tcp_client.control, {'1': self._state['1'] | 0x02})
>         self._attr_is_on = True
>     except Exception as e:
>         _LOGGER.error(f"Failed to turn on {self._name}: {e}")
> 
> async def async_turn_off(self, **kwargs: Any) -> None:
>     """Turn the switch off."""
>     try:
>         if self._wippe == 'wippe1':
>             await self.hass.async_add_executor_job(self._tcp_client.control, {'1': self._state['1'] & ~0x01})
>         elif self._wippe == 'wippe2':
>             await self.hass.async_add_executor_job(self._tcp_client.control, {'1': self._state['1'] & ~0x02})
>         self._attr_is_on = False
>     except Exception as e:
>         _LOGGER.error(f"Failed to turn off {self._name}: {e}")
> ```

Hi guys total new guy here. I believe I found the file that this is referring to. Am I just copying and pasting the entire lot into the file and deleting what was already there?
